### ISSUE TITLE
[Feature] - We need to add CI Workflow into our github repository

### ISSUE THREAD

**Issue by dkbaldwin** [inDevelopme/justaskdavidb-vuestic-ui#10]
## 💭 Summary 

We need to add a GitHub Actions workflow to automate core continuous integration tasks: building the app, linting the codebase, and running tests on every push or pull request. This is critical to enforce quality and fully enable the protections defined in our branch ruleset for main.

## 🧠 Motivation  
- Branch protection rules will be ineffective
- No automated quality control
- Can’t enforce consistency

## ✅ Acceptance Criteria
  
 - [ ] Workflow file committed to .github/workflows/ci.yml
 - [ ] All 3 jobs (build, lint, test) complete successfully on PRs
 - [ ]  Checks appear in pull request Checks tab
 - [ ]  Status checks are selectable in Branch Protection Rules for main

## 🎯 Benefits  

- Automates quality control: No more "oops I forgot to run tests"
- Prevents bugs from being merged by mistake
- Provides visible feedback in pull requests
- Lets you enforce these checks using branch protection rules

## 📎 Notes 

GitHub Actions offers a versatile platform for automating your software development workflows. Here are some common CI workflows you can implement:([[docs.github.com](https://docs.github.com/en/actions?utm_source=chatgpt.com)][1])

---

### 🔧 Common CI Workflows with GitHub Actions

1. **Build and Test**
   Automatically build your application and run tests on every push or pull request.

   ```yaml
   name: Build and Test

   on: [push, pull_request]

   jobs:
     build:
       runs-on: ubuntu-latest
       steps:
         - uses: actions/checkout@v3
         - run: npm ci
         - run: npm run build
         - run: npm test
   ```

2. **Linting**
   Ensure code quality by running linters to catch syntax errors and enforce coding standards.

   ```yaml
   name: Lint Code

   on: [push, pull_request]

   jobs:
     lint:
       runs-on: ubuntu-latest
       steps:
         - uses: actions/checkout@v3
         - run: npm run lint
   ```

3. **Continuous Deployment (CD)**
   Deploy your application automatically after successful builds and tests.

   ```yaml
   name: Deploy

   on:
     push:
       branches:
         - main

   jobs:
     deploy:
       runs-on: ubuntu-latest
       steps:
         - uses: actions/checkout@v3
         - run: npm ci
         - run: npm run build
         - run: npm run deploy
   ```

4. **Scheduled Workflows**
   Run tasks at scheduled intervals, such as nightly builds or periodic maintenance.

   ```yaml
   name: Nightly Build

   on:
     schedule:
       - cron: '0 0 * * *' # Runs every day at midnight

   jobs:
     build:
       runs-on: ubuntu-latest
       steps:
         - uses: actions/checkout@v3
         - run: npm ci
         - run: npm run build
   ```

5. **Matrix Builds**
   Test your application across multiple environments or configurations.

   ```yaml
   name: Matrix Build

   on: [push, pull_request]

   jobs:
     test:
       runs-on: ubuntu-latest
       strategy:
         matrix:
           node-version: [14, 16, 18]
       steps:
         - uses: actions/checkout@v3
         - uses: actions/setup-node@v3
           with:
             node-version: ${{ matrix.node-version }}
         - run: npm ci
         - run: npm test
   ```

---

These workflows can be customized to fit the specific needs of your project. For more examples and detailed guides, you can refer to the [[GitHub Actions documentation](https://docs.github.com/en/actions)](https://[docs.github.com](https://docs.github.com/en/actions?utm_source=chatgpt.com)/en/actions).([docs.github.com][1])

If you need assistance tailoring these workflows to your project's requirements, feel free to ask!

[1]: https://docs.github.com/en/actions?utm_source=chatgpt.com "GitHub Actions documentation - GitHub Docs"
